name: Docker image CI for GHCR

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker tag customer:latest ghcr.io/ishara-usoof/customer:latest
          docker tag products:latest ghcr.io/ishara-usoof/products:latest
          docker tag shopping:latest ghcr.io/ishara-usoof/shopping:latest
          docker tag nginx-proxy:latest ghcr.io/ishara-usoof/nginx-proxy:latest
          docker tag mvertes/alpine-mongo:latest ghcr.io/ishara-usoof/mvertes/alpine-mongo:latest
          docker tag rabbitmq:alpine ghcr.io/ishara-usoof/rabbitmq:alpine
          docker  push ghcr.io/ishara-usoof/customer:latest
          docker  push ghcr.io/ishara-usoof/products:latest
          docker  push ghcr.io/ishara-usoof/shopping:latest
          docker  push ghcr.io/ishara-usoof/nginx-proxy:latest
          docker  push ghcr.io/ishara-usoof/mvertes/alpine-mongo:latest
          docker  push ghcr.io/ishara-usoof/rabbitmq:alpine
          
          
